local_backend: true

backend:
  name: git-gateway
  branch: main
  squash_merges: true

display_url: https://martinjagodic.com/
logo_url: /media/me.jpg
media_folder: static/media/uploads
public_folder: /media/uploads

slug:
  encoding: ascii
  clean_accents: true

aliases:
  - &VISIBLE_IN_CMS {name: visibleInCMS, widget: hidden, default: true}

collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/posts
    create: true
    slug: "{{slug}}"
    filter: {field: visibleInCMS, value: true}
    editor:
      preview: false
    fields: [
      {name: title, widget: string},
      {name: description, widget: text},
      {name: image, widget: image},
      {name: body, widget: markdown},
      *VISIBLE_IN_CMS,
    ]

  - name: general
    label: General
    editor:
      preview: false
    files:
    - label: Site settings
      name: site-settings
      file: config.toml
      fields: [
        {name: title, widget: string},
        {name: params, widget: object, fields: [
          {name: description, widget: text},
          {name: image, widget: image},
        ]},
      ]
    - label: Footer
      name: footer
      file: data/footer.json
      fields: [
        {name: copyright, widget: string}
      ]
